pipeline:
  build:
    image: ubuntu
    privileged: true
    commands:
      - apt update
      - apt install lvm2 -y
      - lvs
      - ls
      - mv coverage.txt coverage.cov
  coverage:
    image: robertstettner/drone-codecov
    secrets: [ codecov_token ]
    debug: true
    files:
      - coverage.cov

